# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=6)),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=500)),
            ],
        ),
    ]
