# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_coursedescription_course_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedescription',
            name='course_time',
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='call_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='cretids',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='days_times',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='instructor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='section_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='session_dates',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='coursedescription',
            name='status_seats',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='course_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='course_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='course_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
