# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20171014_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedescription',
            old_name='cretids',
            new_name='credits',
        ),
    ]
