# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20171014_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDescription',
            new_name='Course',
        ),
    ]
